In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from pandas.api.types import is_numeric_dtype

df = pd.read_csv("../CustomerChurn_App/data/billing.csv")
df

,customerid,billing_date,monthlycharges,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,phone_lines,streaming
0,3d40ba9d86cc7b97612628a924cd63bc,2023-01-31,29.85,DSL,No,Yes,No,No,0,No
1,3d40ba9d86cc7b97612628a924cd63bc,2023-02-28,29.85,DSL,No,Yes,No,No,0,No
2,3d40ba9d86cc7b97612628a924cd63bc,2023-03-31,29.85,DSL,No,Yes,No,No,0,No
3,3d40ba9d86cc7b97612628a924cd63bc,2023-04-30,35.82,DSL,No,Yes,No,No,0,No
4,3d40ba9d86cc7b97612628a924cd63bc,2023-05-31,35.82,DSL,No,Yes,No,No,0,No
...,...,...,...,...,...,...,...,...,...,...
100775,7aea14389aa3d73fd383221574f76778,2023-04-30,70.60,Fiber optic,No,No,No,No,1,No
100776,7aea14389aa3d73fd383221574f76778,2023-05-31,70.60,Fiber optic,No,No,No,No,1,No
100777,7aea14389aa3d73fd383221574f76778,2023-06-30,70.60,Fiber optic,No,No,No,No,1,No
100778,7aea14389aa3d73fd383221574f76778,2023-07-31,70.60,Fiber optic,No,No,No,No,1,No
100779,7aea14389aa3d73fd383221574f76778,2023-08-18,70.60,Fiber optic,No,No,No,No,1,No

In [5]:
def encoded(dataset, options="auto"):
    if options not in ["auto", "one-hot", "label", "ordinal"]:
        raise ValueError("Opción no válida. Usa: 'auto', 'one-hot', 'label' o 'ordinal'.")

    # Auto-detectar codificación
    if options == "auto":
        # Verifica que el DataFrame tenga una sola columna y que esa columna tenga solo 2 valores únicos
        if dataset.shape[1] == 1 and dataset.iloc[:, 0].nunique() <= 2:
            options = "label"
        else:
            options = "one-hot"

    if options == "one-hot":
        encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
        encoded_array = encoder.fit_transform(dataset)
        return pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(dataset.columns))

    elif options == "label":
        if dataset.shape[1] != 1:
            raise ValueError("LabelEncoder solo admite una columna a la vez.")
        encoder = LabelEncoder()
        encoded_col = encoder.fit_transform(dataset.iloc[:, 0])
        return pd.DataFrame(encoded_col, columns=[dataset.columns[0] + "_encoded"])

    elif options == "ordinal":
        encoder = OrdinalEncoder()
        encoded_array = encoder.fit_transform(dataset)
        return pd.DataFrame(encoded_array, columns=dataset.columns)

In [6]:
# TRansformamos las fechas a formato date
df["billing_date"] = pd.to_datetime(df["billing_date"], errors="coerce", format="%Y-%m-%d")

In [8]:
dataset_tenure = pd.DataFrame(pd.read_json("../CustomerChurn_App/data/tenure.json"))
dataset_tenure["date"] = pd.to_datetime(dataset_tenure["date"], errors="coerce", format="%Y-%m-%d")

dataset_tenure

,customerid,date,tenure_months,tenure_penalty
0,3d40ba9d86cc7b97612628a924cd63bc,2023-01-31,6,89.17
1,3d40ba9d86cc7b97612628a924cd63bc,2023-02-28,5,74.31
2,3d40ba9d86cc7b97612628a924cd63bc,2023-03-31,4,59.45
3,3d40ba9d86cc7b97612628a924cd63bc,2023-04-30,3,44.59
4,3d40ba9d86cc7b97612628a924cd63bc,2023-05-31,2,29.72
...,...,...,...,...
26596,167041637430b3d83cd801a7c43369c9,2023-06-30,6,63.44
26597,167041637430b3d83cd801a7c43369c9,2023-07-31,5,52.87
26598,167041637430b3d83cd801a7c43369c9,2023-08-31,4,42.30
26599,167041637430b3d83cd801a7c43369c9,2023-09-30,3,31.72
26600,167041637430b3d83cd801a7c43369c9,2023-10-31,2,21.15

In [9]:
dataset = df.merge(dataset_tenure, on="customerid", how="left")
dataset

,customerid,billing_date,monthlycharges,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,phone_lines,streaming,date,tenure_months,tenure_penalty
0,3d40ba9d86cc7b97612628a924cd63bc,2023-01-31,29.85,DSL,No,Yes,No,No,0,No,2023-01-31,6.0,89.17
1,3d40ba9d86cc7b97612628a924cd63bc,2023-01-31,29.85,DSL,No,Yes,No,No,0,No,2023-02-28,5.0,74.31
2,3d40ba9d86cc7b97612628a924cd63bc,2023-01-31,29.85,DSL,No,Yes,No,No,0,No,2023-03-31,4.0,59.45
3,3d40ba9d86cc7b97612628a924cd63bc,2023-01-31,29.85,DSL,No,Yes,No,No,0,No,2023-04-30,3.0,44.59
4,3d40ba9d86cc7b97612628a924cd63bc,2023-01-31,29.85,DSL,No,Yes,No,No,0,No,2023-05-31,2.0,29.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
318481,7aea14389aa3d73fd383221574f76778,2023-04-30,70.60,Fiber optic,No,No,No,No,1,No,NaT,NaN,NaN
318482,7aea14389aa3d73fd383221574f76778,2023-05-31,70.60,Fiber optic,No,No,No,No,1,No,NaT,NaN,NaN
318483,7aea14389aa3d73fd383221574f76778,2023-06-30,70.60,Fiber optic,No,No,No,No,1,No,NaT,NaN,NaN
318484,7aea14389aa3d73fd383221574f76778,2023-07-31,70.60,Fiber optic,No,No,No,No,1,No,NaT,NaN,NaN
318485,7aea14389aa3d73fd383221574f76778,2023-08-18,70.60,Fiber optic,No,No,No,No,1,No,NaT,NaN,NaN

In [11]:
df_clientes = pd.read_parquet("../CustomerChurn_App/data/clients.parquet")
dataset = dataset.merge(df_clientes, on="customerid", how="right")

dataset = dataset.drop(columns="customerid")
dataset

,billing_date,monthlycharges,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,phone_lines,streaming,date,...,paperlessbilling,paymentmethod,children,contract_date,married,birth_date,churn_date,country,zipcode,contract_channel
0,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-01-31,...,Yes,Electronic check,0,2022-12-22,Yes,1975-05-01,NaT,ES,14576,None
1,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-02-28,...,Yes,Electronic check,0,2022-12-22,Yes,1975-05-01,NaT,ES,14576,None
2,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-03-31,...,Yes,Electronic check,0,2022-12-22,Yes,1975-05-01,NaT,ES,14576,None
3,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-04-30,...,Yes,Electronic check,0,2022-12-22,Yes,1975-05-01,NaT,ES,14576,None
4,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-05-31,...,Yes,Electronic check,0,2022-12-22,Yes,1975-05-01,NaT,ES,14576,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318514,2023-04-30,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,Yes,Electronic check,0,2022-12-11,No,1964-04-02,2023-08-18,ES,11510,None
318515,2023-05-31,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,Yes,Electronic check,0,2022-12-11,No,1964-04-02,2023-08-18,ES,11510,None
318516,2023-06-30,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,Yes,Electronic check,0,2022-12-11,No,1964-04-02,2023-08-18,ES,11510,None
318517,2023-07-31,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,Yes,Electronic check,0,2022-12-11,No,1964-04-02,2023-08-18,ES,11510,None
318518,2023-08-18,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,Yes,Electronic check,0,2022-12-11,No,1964-04-02,2023-08-18,ES,11510,None

In [12]:
# Asegurar que churn_date es datetime
dataset["churn_date"] = pd.to_datetime(dataset["churn_date"], errors="coerce")

# Variable binaria: ¿el cliente se dio de baja?
dataset["churn"] = dataset["churn_date"].notna().astype(int)

# Comprobamos
dataset["churn"].value_counts()

# Creamos la columna con los días de contrato
dataset["dias_de_contrato"] = (
    dataset["churn_date"].fillna(pd.Timestamp.today()) - dataset["contract_date"]
).dt.days

dataset

,billing_date,monthlycharges,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,phone_lines,streaming,date,...,children,contract_date,married,birth_date,churn_date,country,zipcode,contract_channel,churn,dias_de_contrato
0,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-01-31,...,0,2022-12-22,Yes,1975-05-01,NaT,ES,14576,None,0,860.0
1,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-02-28,...,0,2022-12-22,Yes,1975-05-01,NaT,ES,14576,None,0,860.0
2,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-03-31,...,0,2022-12-22,Yes,1975-05-01,NaT,ES,14576,None,0,860.0
3,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-04-30,...,0,2022-12-22,Yes,1975-05-01,NaT,ES,14576,None,0,860.0
4,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-05-31,...,0,2022-12-22,Yes,1975-05-01,NaT,ES,14576,None,0,860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318514,2023-04-30,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,0,2022-12-11,No,1964-04-02,2023-08-18,ES,11510,None,1,250.0
318515,2023-05-31,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,0,2022-12-11,No,1964-04-02,2023-08-18,ES,11510,None,1,250.0
318516,2023-06-30,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,0,2022-12-11,No,1964-04-02,2023-08-18,ES,11510,None,1,250.0
318517,2023-07-31,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,0,2022-12-11,No,1964-04-02,2023-08-18,ES,11510,None,1,250.0
318518,2023-08-18,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,0,2022-12-11,No,1964-04-02,2023-08-18,ES,11510,None,1,250.0

In [15]:
dataset["churn_dia"] = dataset["churn_date"].dt.to_period("d").astype(str)
churn_por_dia = dataset[dataset["churn"] == 1].groupby("churn_dia").size().reset_index(name="n_churns")
dataset["churn"].value_counts()

churn
0    290173
1     28346
Name: count, dtype: int64

In [9]:
# Identificamos las columnas categoricas
categorical_features = dataset.select_dtypes(include=["object"]).columns.tolist()

# Codificamos las columnas
df_encoded = encoded(dataset[categorical_features])

# Columnas numéricas
numerical_features = dataset.select_dtypes(include=["number"]).columns.tolist()

# Concatenar codificadas + numéricas
df_encoded = pd.concat([encoded(dataset[categorical_features]), dataset[numerical_features]], axis=1)

"churn" in df_encoded.columns

False

In [10]:
df_encoded.to_parquet("data/dataset_encoded.parquet", index=False)
dataset.to_parquet("data/dataset_completo.parquet", index=False)

In [25]:
def encode_binary_columns(df):
    df_encoded = df.copy()
    for col in df.columns:
        if df[col].nunique(dropna=True) == 2 and not is_numeric_dtype(df[col]):
            encoder = LabelEncoder()
            df_encoded[col + "_encoded"] = encoder.fit_transform(df[col])
    return df_encoded


def encode_ternary_columns(df):
    df_encoded = df.copy()
    for col in df.columns:
        if df[col].nunique(dropna=True) == 3 and not is_numeric_dtype(df[col]):
            encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
            transformed = encoder.fit_transform(df[[col]])
            new_cols = [f"{col}_{cat}" for cat in encoder.categories_[0]]
            df_onehot = pd.DataFrame(transformed, columns=new_cols, index=df.index)
            df_encoded = pd.concat([df_encoded, df_onehot], axis=1)
    return df_encoded


# Uso
dataset_partial_encoded = encode_binary_columns(dataset)
dataset_partial_encoded = encode_ternary_columns(dataset_partial_encoded)
dataset_partial_encoded

,billing_date,monthlycharges,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,phone_lines,streaming,date,...,deviceprotection_Yes,deviceprotection_nan,techsupport_No,techsupport_No internet service,techsupport_Yes,techsupport_nan,contract_channel_Internet,contract_channel_Phone,contract_channel_Store,contract_channel_None
0,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-01-31,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-02-28,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-03-31,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-04-30,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,2023-01-31,29.85,DSL,No,Yes,No,No,0.0,No,2023-05-31,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318514,2023-04-30,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
318515,2023-05-31,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
318516,2023-06-30,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
318517,2023-07-31,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
318518,2023-08-18,70.60,Fiber optic,No,No,No,No,1.0,No,NaT,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [26]:
dataset_partial_encoded.to_parquet("data/dataset_partial_encoded.parquet", index=False)